package io.github.minorg.whoisclient.parser;

import io.github.minorg.whoisclient.Gazetteers;
import io.github.minorg.whoisclient.WhoisRecord;

public class WhoisAdministrativeContactFieldParser extends WhoisRegistrantFieldParser {
    public WhoisAdministrativeContactFieldParser(final Gazetteers gazetteers) {
        super(WhoisRecord.FieldMetadata.ADMINISTRATIVE_CONTACT, gazetteers, new String[] {
                "   Administrative Contact:[ ]*\\n      (?<organization>.*)\\n      (?<name>.*)\\n      (?<street>.*)\\n      (?<city>.*), (?<state>.*) (?<postalcode>.*)\\n      (?<country>.*)\\n(?:      Phone: (?<phone>.*)\\n)?      Email: (?<email>.*)\\n", // Corporate
                                                                                                                                                                                                                                                                   // Domains,
                                                                                                                                                                                                                                                                   // Inc.
                "Administrative Contact:\\n  (?<name>.+)\\n  (?<street1>.+)\\n(?:  (?<street2>.*)\\n)?(?:  (?<street3>.*)\\n)?  (?<postalcode>.+), (?<city>.+)\\n  (?<country>.+)\\n  (?<phone>.+)\\n  (?<email>.+)\\n\\n", // OVH
                "(?:Admin ID:(?<handle>.+)\\n)?Admin Name:(?<name>.*)\\n(?:Admin Organization:(?<organization>.*)\\n)?Admin Street1?:(?<street1>.*)\\n(?:Admin Street2:(?<street2>.*)\\n)?(?:Admin Street3:(?<street3>.*)\\n)?Admin City:(?<city>.*)\\nAdmin State/Province:(?<state>.*)\\nAdmin Postal Code:(?<postalcode>.*)\\nAdmin Country:(?<country>.*)\\nAdmin Phone:(?<phone>.*)\\n(?:Admin Phone Ext.:(?<phoneext>.*)\\n)?(?:Admin FAX:(?<fax>.*)\\n)?(?:Admin FAX Ext.:(?<faxext>.*)\\n)?Admin Email:(?<email>.*)", // Public
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Interest
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Registry
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // (.org),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // nic.pw,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // No-IP.com
                "Admin(?:istrative)? ID:(?<handle>.+)\\nAdmin(?:istrative)? Name:(?<name>.*)\\n(?:Admin(?:istrative)? Organization:(?<organization>.*)\\n)?Admin(?:istrative)? Address1?:(?<street1>.*)\\n(?:Admin(?:istrative)? Address2:(?<street2>.*)\\n)?(?:Admin(?:istrative)? Address3:(?<street3>.*)\\n)?Admin(?:istrative)? City:(?<city>.*)\\nAdmin(?:istrative)? State/Province:(?<state>.*)\\nAdmin(?:istrative)? Country/Economy:(?<country>.*)\\nAdmin(?:istrative)? Postal Code:(?<postalcode>.*)\\nAdmin(?:istrative)? Phone:(?<phone>.*)\\n(?:Admin(?:istrative)? Phone Ext.:(?<phoneext>.*)\\n)?(?:Admin(?:istrative)? FAX:(?<fax>.*)\\n)?(?:Admin(?:istrative)? FAX Ext.:(?<faxext>.*)\\n)?Admin(?:istrative)? E-mail:(?<email>.*)", // .ME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // DotAsia
                "Administrative Contact ID:\\s*(?<handle>.+)\\nAdministrative Contact Name:\\s*(?<name>.+)\\nAdministrative Contact Organization:\\s*(?<organization>.*)\\nAdministrative Contact Address1:\\s*(?<street1>.+)\\nAdministrative Contact Address2:\\s*(?<street2>.*)\\nAdministrative Contact City:\\s*(?<city>.+)\\nAdministrative Contact State/Province:\\s*(?<state>.+)\\nAdministrative Contact Postal Code:\\s*(?<postalcode>.+)\\nAdministrative Contact Country:\\s*(?<country>.+)\\nAdministrative Contact Country Code:\\s*(?<countrycode>.+)\\nAdministrative Contact Phone Number:\\s*(?<phone>.+)\\nAdministrative Contact Email:\\s*(?<email>.+)\\n", // .CO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Internet
                "Admin Contact: (?<handle>.+)\\nAdmin Organization: (?<organization>.+)\\nAdmin Name: (?<name>.+)\\nAdmin Street: (?<street>.+)\\nAdmin City: (?<city>.+)\\nAdmin State: (?<state>.+)\\nAdmin Postal Code: (?<postalcode>.+)\\nAdmin Country: (?<country>.+)\\nAdmin Phone: (?<phone>.*)\\nAdmin Phone Ext: (?<phoneext>.*)\\nAdmin Fax: (?<fax>.*)\\nAdmin Fax Ext: (?<faxext>.*)\\nAdmin Email: (?<email>.*)\\n", // Key-Systems
                                                                                                                                                                                                                                                                                                                                                                                                                                    // GmbH
                "(?:Admin ID:[ ]*(?<handle>.*)\\n)?Admin[ ]*Name:[ ]*(?<name>.*)\\n(?:Admin[ ]*Organization:[ ]*(?<organization>.*)\\n)?Admin[ ]*Street:[ ]*(?<street1>.+)\\n(?:Admin[ ]*Street:[ ]*(?<street2>.+)\\n)?(?:Admin[ ]*Street:[ ]*(?<street3>.+)\\n)?Admin[ ]*City:[ ]*(?<city>.+)\\nAdmin[ ]*State(?:\\/Province)?:[ ]*(?<state>.*)\\nAdmin[ ]*Postal[ ]*Code:[ ]*(?<postalcode>.+)\\nAdmin[ ]*Country:[ ]*(?<country>.+)\\n(?:Admin[ ]*Phone:[ ]*(?<phone>.*)\\n)?(?:Admin[ ]*Phone[ ]*Ext:[ ]*(?<phoneext>.*)\\n)?(?:Admin[ ]*Fax:[ ]*(?<fax>.*)\\n)?(?:Admin[ ]*Fax[ ]*Ext:\\s*?(?<faxext>.*)\\n)?(?:Admin[ ]*Email:[ ]*(?<email>.+)\\n)?", // WildWestDomains,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // GoDaddy,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Namecheap/eNom,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Ascio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Musedoma
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // (.museum),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // EuroDNS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // nic.ps
                "Administrative Contact\\n(?:    (?<organization>.+)\\n)?    (?<name>.+)\\n    Email:(?<email>.+)\\n    (?<street1>.+)\\n(?:    (?<street2>.+)\\n)?    (?<postalcode>.+) (?<city>.+)\\n    (?<country>.+)\\n    Tel: (?<phone>.+)\\n\\n", // internet.bs
                " Administrative Contact Details:[ ]*\\n    (?<organization>.*)\\n    (?<name>.*)[ ]{2,}\\((?<email>.*)\\)\\n    (?<street1>.*)\\n(?:    (?<street2>.*)\\n)?(?:    (?<street3>.*)\\n)?    (?<city>.*)\\n    (?<state>.*),(?<postalcode>.*)\\n    (?<country>.*)\\n    Tel. (?<phone>.*)", // Whois.com
                "admin-id:[ ]*(?<handle>.*)\\n(?:admin-organization:[ ]*(?<organization>.*)\\n)?admin-name:[ ]*(?<name>.*)\\nadmin-street:[ ]*(?<street>.*)\\nadmin-city:[ ]*(?<city>.*)\\nadmin-zip:[ ]*(?<postalcode>.*)\\nadmin-country:[ ]*(?<country>.*)\\n(?:admin-phone:[ ]*(?<phone>.*)\\n)?(?:admin-fax:[ ]*(?<fax>.*)\\n)?admin-email:[ ]*(?<email>.*)", // InterNetworX
                "Administrative Contact:\\n admin_org: (?<organization>.*)\\n admin_name: (?<name>.*)\\n admin_email: (?<email>.*)\\n admin_address: (?<address>.*)\\n admin_city: (?<city>.*)\\n admin_state: (?<state>.*)\\n admin_zip: (?<postalcode>.*)\\n admin_country: (?<country>.*)\\n admin_phone: (?<phone>.*)", // Bellnames
                "Administrative Contact ID:(?<handle>.*)\\nAdministrative Contact Name:(?<name>.*)\\n(?:Administrative Contact Organization:(?<organization>.*)\\n)?Administrative Contact Address1:(?<street1>.*)\\n(?:Administrative Contact Address2:(?<street2>.*)\\n)?(?:Administrative Contact Address3:(?<street3>.*)\\n)?Administrative Contact City:(?<city>.*)\\n(?:Administrative Contact State/Province:(?<state>.*)\\n)?(?:Administrative Contact Postal Code:(?<postalcode>.*)\\n)?Administrative Contact Country:(?<country>.*)\\nAdministrative Contact Country Code:.*\\nAdministrative Contact Phone Number:(?<phone>.*)\\n(?:Administrative Contact Facsimile Number:(?<facsimile>.*)\\n)?Administrative Contact Email:(?<email>.*)", // .US,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // .biz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // (NeuStar),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // .buzz,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // .moe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // (Interlink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Co.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Ltd.)
                "Admin Contact\\n  Name:             (?<name>.+)\\n(?:  Organization:     (?<organization>.+)\\n)?  ContactID:        (?<handle>.+)\\n(?:  Address:          (?<street1>.+)\\n(?:                    (?<street2>.+)\\n(?:                    (?<street3>.+)\\n)?)?                    (?<city>.+)\\n                    (?<postalcode>.+)\\n                    (?<state>.+)\\n                    (?<country>.+)\\n)?(?:  Created:          (?<creationdate>.+)\\n)?(?:  Last Update:      (?<changedate>.+)\\n)?", // nic.it
                "Admin Name[.]* (?<name>.*)\\n  Admin Address[.]* (?<street1>.*)\\n  Admin Address[.]* (?<street2>.*)\\n(?:  Admin Address[.]* (?<street3>.*)\\n)?  Admin Address[.]* (?<city>.*)\\n  Admin Address[.]* (?<postalcode>.*)\\n  Admin Address[.]* (?<state>.*)\\n  Admin Address[.]* (?<country>.*)\\n  Admin Email[.]* (?<email>.*)\\n  Admin Phone[.]* (?<phone>.*)\\n  Admin Fax[.]* (?<fax>.*)", // Melbourne
                                                                                                                                                                                                                                                                                                                                                                                                                   // IT
                "Administrative contact:\\n(?:  (?<organization>.+)\\n)?  (?<name>.+)\\n  (?<email>.+)\\n  (?<street>.+)\\n  (?<city>.+), (?<state>.+) (?<postalcode>.+) (?<country>.+)\\n  Phone: (?<phone>.*)\\n  Fax: (?<fax>.*)\\n", // Fabulous.com
                "admin-c-name:\\s*(?<name>.+)\\nadmin-c-type:\\s*(?<type>.+)\\nadmin-c-address:\\s*(?<street>.+)\\nadmin-c-postcode:\\s*(?<postalcode>.+)\\nadmin-c-city:\\s*(?<city>.+)\\nadmin-c-country:\\s*(?<country>.+)\\n(?:admin-c-phone:\\s*(?<phone>.+)\\n)?(?:admin-c-email:\\s*(?<email>.+)\\n)?", // Hetzner
                "Tech Contact Information :[ ]*\\n[ ]+(?<firstname>.*)\\n[ ]+(?<lastname>.*)\\n[ ]+(?<organization>.*)\\n[ ]+(?<email>.*)\\n[ ]+(?<street>.*)\\n[ ]+(?<city>.*)\\n[ ]+(?<postalcode>.*)\\n[ ]+(?<phone>.*)\\n[ ]+(?<fax>.*)\\n\\n", // GAL
                                                                                                                                                                                                                                                    // Communication
                "   Administrative contact:\\n      (?<name>.+)\\n      (?<organization>.*)\\n      (?<street>.+)\\n      (?<city>.+) (?<state>\\S+),[ ]+(?<postalcode>.+)\\n      (?<country>.+)\\n      (?<email>.+)\\n      (?<phone>.*)\\n      (?<fax>.*)", // .am
                "Administrative Contact:\\n   Name:           (?<name>.+)\\n   City:           (?<city>.+)\\n   State:          (?<state>.+)\\n   Country:        (?<country>.+)\\n", // Akky
                                                                                                                                                                                      // (.com.mx)
                "\\[Tech-C\\]\\nType: (?<type>.+)\\nName: (?<name>.+)\\n(Organisation: (?<organization>.+)\\n){0,1}(Address: (?<street1>.+)\\n){1}(Address: (?<street2>.+)\\n){0,1}(Address: (?<street3>.+)\\n){0,1}(Address: (?<street4>.+)\\n){0,1}PostalCode: (?<postalcode>.+)\\nCity: (?<city>.+)\\nCountryCode: (?<country>[A-Za-z]{2})\\nPhone: (?<phone>.+)\\nFax: (?<fax>.+)\\nEmail: (?<email>.+)\\n(Remarks: (?<remark>.+)\\n){0,1}Changed: (?<changed>.+)", // DeNIC
                "   Administrative Contact:\\n      (?<name>.+)  (?<email>.+)\\n      (?<phone>.*)\\n      (?<fax>.*)\\n", // .com.tw
                                                                                                                           // (Western
                                                                                                                           // registrars)
                "Administrative Contact Information:\\n\\n(?:Given name: (?<firstname>.+)\\n)?(?:Family name: (?<lastname>.+)\\n)?(?:Company name: (?<organization>.+)\\n)?Address: (?<street>.+)\\nCountry: (?<country>.+)\\nPhone: (?<phone>.*)\\nFax: (?<fax>.*)\\nEmail: (?<email>.+)\\n(?:Account Name: (?<handle>.+)\\n)?", // HKDNR
                                                                                                                                                                                                                                                                                                                                  // (.hk)
                "ADMIN ID:(?<handle>.+)\\nADMIN Name:(?<name>.*)\\n(?:ADMIN Organization:(?<organization>.*)\\n)?ADMIN Street1:(?<street1>.+?)\\n(?:ADMIN Street2:(?<street2>.+?)\\n(?:ADMIN Street3:(?<street3>.+?)\\n)?)?ADMIN City:(?<city>.+)\\nADMIN State:(?<state>.*)\\nADMIN Postal Code:(?<postalcode>.+)\\nADMIN Country:(?<country>[A-Z]+)\\nADMIN Phone:(?<phone>.*?)\\nADMIN Fax:(?<fax>.*)\\nADMIN Email:(?<email>.+)\\n", // Realtime
                                                                                                                                                                                                                                                                                                                                                                                                                                         // Register
        });
    }
}
