package io.github.minorg.whoisclient.parser;

import io.github.minorg.whoisclient.Gazetteers;
import io.github.minorg.whoisclient.WhoisRecord;

public class WhoisBillingContactFieldParser extends WhoisRegistrantFieldParser {
    public WhoisBillingContactFieldParser(final Gazetteers gazetteers) {
        super(WhoisRecord.FieldMetadata.BILLING_CONTACT, gazetteers, new String[] {
                "(?:Billing ID:(?<handle>.+)\\n)?Billing Name:(?<name>.*)\\nBilling Organization:(?<organization>.*)\\nBilling Street1:(?<street1>.*)\\n(?:Billing Street2:(?<street2>.*)\\n)?(?:Billing Street3:(?<street3>.*)\\n)?Billing City:(?<city>.*)\\nBilling State/Province:(?<state>.*)\\nBilling Postal Code:(?<postalcode>.*)\\nBilling Country:(?<country>.*)\\nBilling Phone:(?<phone>.*)\\n(?:Billing Phone Ext.:(?<phoneext>.*)\\n)?(?:Billing FAX:(?<fax>.*)\\n)?(?:Billing FAX Ext.:(?<faxext>.*)\\n)?Billing Email:(?<email>.*)", // nic.pw,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // No-IP.com
                "Billing ID:(?<handle>.+)\\nBilling Name:(?<name>.*)\\n(?:Billing Organization:(?<organization>.*)\\n)?Billing Address1?:(?<street1>.*)\\n(?:Billing Address2:(?<street2>.*)\\n)?(?:Billing Address3:(?<street3>.*)\\n)?Billing City:(?<city>.*)\\nBilling State/Province:(?<state>.*)\\nBilling Country/Economy:(?<country>.*)\\nBilling Postal Code:(?<postalcode>.*)\\nBilling Phone:(?<phone>.*)\\n(?:Billing Phone Ext.:(?<phoneext>.*)\\n)?(?:Billing FAX:(?<fax>.*)\\n)?(?:Billing FAX Ext.:(?<faxext>.*)\\n)?Billing E-mail:(?<email>.*)", // DotAsia
                "Billing Contact ID:\\s*(?<handle>.+)\\nBilling Contact Name:\\s*(?<name>.+)\\nBilling Contact Organization:\\s*(?<organization>.*)\\nBilling Contact Address1:\\s*(?<street1>.+)\\nBilling Contact Address2:\\s*(?<street2>.*)\\nBilling Contact City:\\s*(?<city>.+)\\nBilling Contact State/Province:\\s*(?<state>.+)\\nBilling Contact Postal Code:\\s*(?<postalcode>.+)\\nBilling Contact Country:\\s*(?<country>.+)\\nBilling Contact Country Code:\\s*(?<countrycode>.+)\\nBilling Contact Phone Number:\\s*(?<phone>.+)\\nBilling Contact Email:\\s*(?<email>.+)\\n", // .CO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Internet
                "Billing Contact: (?<handle>.+)\\nBilling Organization: (?<organization>.+)\\nBilling Name: (?<name>.+)\\nBilling Street: (?<street>.+)\\nBilling City: (?<city>.+)\\nBilling Postal Code: (?<postalcode>.+)\\nBilling State: (?<state>.+)\\nBilling Country: (?<country>.+)\\nBilling Phone: (?<phone>.*)\\nBilling Phone Ext: (?<phoneext>.*)\\nBilling Fax: (?<fax>.*)\\nBilling Fax Ext: (?<faxext>.*)\\nBilling Email: (?<email>.*)\\n", // Key-Systems
                                                                                                                                                                                                                                                                                                                                                                                                                                                              // GmbH
                "(?:Billing ID:[ ]*(?<handle>.*)\\n)?Billing[ ]*Name:[ ]*(?<name>.*)\\n(?:Billing[ ]*Organization:[ ]*(?<organization>.*)\\n)?Billing[ ]*Street:[ ]*(?<street1>.+)\\n(?:Billing[ ]*Street:[ ]*(?<street2>.+)\\n)?Billing[ ]*City:[ ]*(?<city>.+)\\nBilling[ ]*State\\/Province:[ ]*(?<state>.+)\\nBilling[ ]*Postal[ ]*Code:[ ]*(?<postalcode>.+)\\nBilling[ ]*Country:[ ]*(?<country>.+)\\n(?:Billing[ ]*Phone:[ ]*(?<phone>.*)\\n)?(?:Billing[ ]*Phone[ ]*Ext:[ ]*(?<phoneext>.*)\\n)?(?:Billing[ ]*Fax:[ ]*(?<fax>.*)\\n)?(?:Billing[ ]*Fax[ ]*Ext:\\s*?(?<faxext>.*)\\n)?(?:Billing[ ]*Email:[ ]*(?<email>.+)\\n)?", // Musedoma
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // (.museum)
                "Billing Contact:\\n  (?<name>.+)\\n  (?<street1>.+)\\n(?:  (?<street2>.*)\\n)?(?:  (?<street3>.*)\\n)?  (?<postalcode>.+), (?<city>.+)\\n  (?<country>.+)\\n  (?<phone>.+)\\n  (?<email>.+)\\n\\n", // OVH
                " Billing Contact Details:[ ]*\\n    (?<organization>.*)\\n    (?<name>.*)[ ]{2,}\\((?<email>.*)\\)\\n    (?<street1>.*)\\n(?:    (?<street2>.*)\\n)?(?:    (?<street3>.*)\\n)?    (?<city>.*)\\n    (?<state>.*),(?<postalcode>.*)\\n    (?<country>.*)\\n    Tel. (?<phone>.*)", // Whois.com
                "billing-id:[ ]*(?<handle>.*)\\n(?:billing-organization:[ ]*(?<organization>.*)\\n)?billing-name:[ ]*(?<name>.*)\\nbilling-street:[ ]*(?<street>.*)\\nbilling-city:[ ]*(?<city>.*)\\nbilling-zip:[ ]*(?<postalcode>.*)\\nbilling-country:[ ]*(?<country>.*)\\n(?:billing-phone:[ ]*(?<phone>.*)\\n)?(?:billing-fax:[ ]*(?<fax>.*)\\n)?billing-email:[ ]*(?<email>.*)", // InterNetworX
                "Billing Contact:\\n bill_org: (?<organization>.*)\\n bill_name: (?<name>.*)\\n bill_email: (?<email>.*)\\n bill_address: (?<address>.*)\\n bill_city: (?<city>.*)\\n bill_state: (?<state>.*)\\n bill_zip: (?<postalcode>.*)\\n bill_country: (?<country>.*)\\n bill_phone: (?<phone>.*)", // Bellnames
                "Billing Contact ID:(?<handle>.*)\\nBilling Contact Name:(?<name>.*)\\n(?:Billing Contact Organization:(?<organization>.*)\\n)?Billing Contact Address1:(?<street1>.*)\\n(?:Billing Contact Address2:(?<street2>.*)\\n)?(?:Billing Contact Address3:(?<street3>.*)\\n)?Billing Contact City:(?<city>.*)\\n(?:Billing Contact State/Province:(?<state>.*)\\n)?(?:Billing Contact Postal Code:(?<postalcode>.*)\\n)?Billing Contact Country:(?<country>.*)\\nBilling Contact Country Code:.*\\nBilling Contact Phone Number:(?<phone>.*)\\n(?:Billing Contact Facsimile Number:(?<facsimile>.*)\\n)?Billing Contact Email:(?<email>.*)", // .US,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // .biz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // (NeuStar),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // .buzz,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // .moe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // (Interlink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // Co.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // Ltd.)
                "Billing contact:\\n(?:  (?<organization>.+)\\n)?  (?<name>.+)\\n  (?<email>.+)\\n  (?<street>.+)\\n  (?<city>.+), (?<state>.+) (?<postalcode>.+) (?<country>.+)\\n  Phone: (?<phone>.*)\\n  Fax: (?<fax>.*)\\n", // Fabulous.com
                "Billing Contact Information :[ ]*\\n[ ]+(?<firstname>.*)\\n[ ]+(?<lastname>.*)\\n[ ]+(?<organization>.*)\\n[ ]+(?<email>.*)\\n[ ]+(?<street>.*)\\n[ ]+(?<city>.*)\\n[ ]+(?<postalcode>.*)\\n[ ]+(?<phone>.*)\\n[ ]+(?<fax>.*)\\n\\n", // GAL
                                                                                                                                                                                                                                                       // Communication
                "Billing Contact:\\n   Name:           (?<name>.+)\\n   City:           (?<city>.+)\\n   State:          (?<state>.+)\\n   Country:        (?<country>.+)\\n", // Akky
                                                                                                                                                                               // (.com.mx)
                "BILLING ID:(?<handle>.+)\\nBILLING Name:(?<name>.*)\\n(?:BILLING Organization:(?<organization>.*)\\n)?BILLING Street1:(?<street1>.+?)\\n(?:BILLING Street2:(?<street2>.+?)\\n(?:BILLING Street3:(?<street3>.+?)\\n)?)?BILLING City:(?<city>.+)\\nBILLING State:(?<state>.*)\\nBILLING Postal Code:(?<postalcode>.+)\\nBILLING Country:(?<country>[A-Z]+)\\nBILLING Phone:(?<phone>.*?)\\nBILLING Fax:(?<fax>.*)\\nBILLING Email:(?<email>.+)\\n", // Realtime
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Register
        });
    }
}
