package io.github.minorg.whoisclient.parser;

import io.github.minorg.whoisclient.Gazetteers;
import io.github.minorg.whoisclient.ParsedWhoisRecord;

public class WhoisTechnicalContactFieldParser extends WhoisRegistrantFieldParser {
    public WhoisTechnicalContactFieldParser(final Gazetteers gazetteers) {
        super(ParsedWhoisRecord.FieldMetadata.TECHNICAL_CONTACT, gazetteers, new String[] {
                "   Technical Contact:[ ]*\\n      (?<organization>.*)\\n      (?<name>.*)\\n      (?<street>.*)\\n      (?<city>.*), (?<state>.*) (?<postalcode>.*)\\n      (?<country>.*)\\n(?:      Phone: (?<phone>.*)\\n)?      Email: (?<email>.*)\\n", // Corporate
                                                                                                                                                                                                                                                              // Domains,
                                                                                                                                                                                                                                                              // Inc.
                "Technical Contact:\\n  (?<name>.+)\\n  (?<street1>.+)\\n(?:  (?<street2>.*)\\n)?(?:  (?<street3>.*)\\n)?  (?<postalcode>.+), (?<city>.+)\\n  (?<country>.+)\\n  (?<phone>.+)\\n  (?<email>.+)\\n\\n", // OVH
                "(?:Tech ID:(?<handle>.+)\\n)?Tech Name:(?<name>.*)\\n(:?Tech Organization:(?<organization>.*)\\n)?Tech Street1?:(?<street1>.*)\\n(?:Tech Street2:(?<street2>.*)\\n)?(?:Tech Street3:(?<street3>.*)\\n)?Tech City:(?<city>.*)\\nTech State/Province:(?<state>.*)\\nTech Postal Code:(?<postalcode>.*)\\nTech Country:(?<country>.*)\\nTech Phone:(?<phone>.*)\\n(?:Tech Phone Ext.:(?<phoneext>.*)\\n)?(?:Tech FAX:(?<fax>.*)\\n)?(?:Tech FAX Ext.:(?<faxext>.*)\\n)?Tech Email:(?<email>.*)", // Public
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // Interest
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // Registry
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // (.org),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // nic.pw,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // No-IP.com
                "Tech(?:nical)? ID:(?<handle>.+)\\nTech(?:nical)? Name:(?<name>.*)\\n(?:Tech(?:nical)? Organization:(?<organization>.*)\\n)?Tech(?:nical)? Address1?:(?<street1>.*)\\n(?:Tech(?:nical)? Address2:(?<street2>.*)\\n)?(?:Tech(?:nical)? Address3:(?<street3>.*)\\n)?Tech(?:nical)? City:(?<city>.*)\\nTech(?:nical)? State/Province:(?<state>.*)\\nTech(?:nical)? Country/Economy:(?<country>.*)\\nTech(?:nical)? Postal Code:(?<postalcode>.*)\\nTech(?:nical)? Phone:(?<phone>.*)\\n(?:Tech(?:nical)? Phone Ext.:(?<phoneext>.*)\\n)?(?:Tech(?:nical)? FAX:(?<fax>.*)\\n)?(?:Tech(?:nical)? FAX Ext.:(?<faxext>.*)\\n)?Tech(?:nical)? E-mail:(?<email>.*)", // .ME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // DotAsia
                "Technical Contact ID:\\s*(?<handle>.+)\\nTechnical Contact Name:\\s*(?<name>.+)\\nTechnical Contact Organization:\\s*(?<organization>.*)\\nTechnical Contact Address1:\\s*(?<street1>.+)\\nTechnical Contact Address2:\\s*(?<street2>.*)\\nTechnical Contact City:\\s*(?<city>.+)\\nTechnical Contact State/Province:\\s*(?<state>.+)\\nTechnical Contact Postal Code:\\s*(?<postalcode>.+)\\nTechnical Contact Country:\\s*(?<country>.+)\\nTechnical Contact Country Code:\\s*(?<countrycode>.+)\\nTechnical Contact Phone Number:\\s*(?<phone>.+)\\nTechnical Contact Email:\\s*(?<email>.+)\\n", // .CO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Internet
                "Tech Contact: (?<handle>.+)\\nTech Organization: (?<organization>.+)\\nTech Name: (?<name>.+)\\nTech Street: (?<street>.+)\\nTech City: (?<city>.+)\\nTech Postal Code: (?<postalcode>.+)\\nTech State: (?<state>.+)\\nTech Country: (?<country>.+)\\nTech Phone: (?<phone>.*)\\nTech Phone Ext: (?<phoneext>.*)\\nTech Fax: (?<fax>.*)\\nTech Fax Ext: (?<faxext>.*)\\nTech Email: (?<email>.*)\\n", // Key-Systems
                                                                                                                                                                                                                                                                                                                                                                                                                       // GmbH
                "(?:Tech ID:[ ]*(?<handle>.*)\\n)?Tech[ ]*Name:[ ]*(?<name>.*)\\n(?:Tech[ ]*Organization:[ ]*(?<organization>.*)\\n)?Tech[ ]*Street:[ ]*(?<street1>.+)\\n(?:Tech[ ]*Street:[ ]*(?<street2>.+)\\n)?(?:Tech[ ]*Street:[ ]*(?<street3>.+)\\n)?Tech[ ]*City:[ ]*(?<city>.+)\\nTech[ ]*State(?:\\/Province)?:[ ]*(?<state>.*)\\nTech[ ]*Postal[ ]*Code:[ ]*(?<postalcode>.+)\\nTech[ ]*Country:[ ]*(?<country>.+)\\n(?:Tech[ ]*Phone:[ ]*(?<phone>.*)\\n)?(?:Tech[ ]*Phone[ ]*Ext:[ ]*(?<phoneext>.*)\\n)?(?:Tech[ ]*Fax:[ ]*(?<fax>.*)\\n)?(?:Tech[ ]*Fax[ ]*Ext:\\s*?(?<faxext>.*)\\n)?(?:Tech[ ]*Email:[ ]*(?<email>.+)\\n)?", // WildWestDomains,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // GoDaddy,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Namecheap/eNom,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Ascio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Musedoma
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // (.museum),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // EuroDNS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // nic.ps
                "Technical Contact\\n(?:    (?<organization>.+)\\n)?    (?<name>.+)\\n    Email:(?<email>.+)\\n    (?<street1>.+)\\n(?:    (?<street2>.+)\\n)?    (?<postalcode>.+) (?<city>.+)\\n    (?<country>.+)\\n    Tel: (?<phone>.+)\\n\\n", // internet.bs
                " Technical Contact Details:[ ]*\\n    (?<organization>.*)\\n    (?<name>.*)[ ]{2,}\\((?<email>.*)\\)\\n    (?<street1>.*)\\n(?:    (?<street2>.*)\\n)?(?:    (?<street3>.*)\\n)?    (?<city>.*)\\n    (?<state>.*),(?<postalcode>.*)\\n    (?<country>.*)\\n    Tel. (?<phone>.*)", // Whois.com
                "tech-id:[ ]*(?<handle>.*)\\n(?:tech-organization:[ ]*(?<organization>.*)\\n)?tech-name:[ ]*(?<name>.*)\\ntech-street:[ ]*(?<street>.*)\\ntech-city:[ ]*(?<city>.*)\\ntech-zip:[ ]*(?<postalcode>.*)\\ntech-country:[ ]*(?<country>.*)\\n(?:tech-phone:[ ]*(?<phone>.*)\\n)?(?:tech-fax:[ ]*(?<fax>.*)\\n)?tech-email:[ ]*(?<email>.*)", // InterNetworX
                "Technical Contact:\\n tech_org: (?<organization>.*)\\n tech_name: (?<name>.*)\\n tech_email: (?<email>.*)\\n tech_address: (?<address>.*)\\n tech_city: (?<city>.*)\\n tech_state: (?<state>.*)\\n tech_zip: (?<postalcode>.*)\\n tech_country: (?<country>.*)\\n tech_phone: (?<phone>.*)", // Bellnames
                "Technical contact:\\n(?<name>[\\S\\s]+)\\n(?<street>.+)\\n(?<postalcode>[A-Z0-9-]+)\\s+(?<city>.+)\\n(?<country>.+)\\n\\n", // nic.ch
                "Tech Contact ID:[ ]*(?<handle>.+)\\nTech Contact Name:[ ]*(?<name>.+)", // .au
                "Technical Contact ID:(?<handle>.*)\\nTechnical Contact Name:(?<name>.*)\\n(?:Technical Contact Organization:(?<organization>.*)\\n)?Technical Contact Address1:(?<street1>.*)\\n(?:Technical Contact Address2:(?<street2>.*)\\n)?(?:Technical Contact Address3:(?<street3>.*)\\n)?Technical Contact City:(?<city>.*)\\n(?:Technical Contact State/Province:(?<state>.*)\\n)?(?:Technical Contact Postal Code:(?<postalcode>.*)\\n)?Technical Contact Country:(?<country>.*)\\nTechnical Contact Country Code:.*\\nTechnical Contact Phone Number:(?<phone>.*)\\n(?:Technical Contact Facsimile Number:(?<facsimile>.*)\\n)?Technical Contact Email:(?<email>.*)", // .US,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // .biz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // (NeuStar),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // .buzz,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // .moe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // (Interlink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Co.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Ltd.)
                "Technical Contacts\\n  Name:             (?<name>.+)\\n(?:  Organization:     (?<organization>.+)\\n)?  ContactID:        (?<handle>.+)\\n(?:  Address:          (?<street1>.+)\\n(?:                    (?<street2>.+)\\n(?:                    (?<street3>.+)\\n)?)?                    (?<city>.+)\\n                    (?<postalcode>.+)\\n                    (?<state>.+)\\n                    (?<country>.+)\\n)?(?:  Created:          (?<creationdate>.+)\\n)?(?:  Last Update:      (?<changedate>.+)\\n)?", // nic.it
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // //
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // NOTE:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Why
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // does
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // this
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // say
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // 'Contacts'?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Can
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // it
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // have
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // multiple?
                "Tech Name[.]* (?<name>.*)\\n  Tech Address[.]* (?<street1>.*)\\n  Tech Address[.]* (?<street2>.*)\\n(?:  Tech Address[.]* (?<street3>.*)\\n)?  Tech Address[.]* (?<city>.*)\\n  Tech Address[.]* (?<postalcode>.*)\\n  Tech Address[.]* (?<state>.*)\\n  Tech Address[.]* (?<country>.*)\\n  Tech Email[.]* (?<email>.*)\\n  Tech Phone[.]* (?<phone>.*)\\n  Tech Fax[.]* (?<fax>.*)", // Melbourne
                                                                                                                                                                                                                                                                                                                                                                                                        // IT
                "Technical contact:\\n(?:  (?<organization>.+)\\n)?  (?<name>.+)\\n  (?<email>.+)\\n  (?<street>.+)\\n  (?<city>.+), (?<state>.+) (?<postalcode>.+) (?<country>.+)\\n  Phone: (?<phone>.*)\\n  Fax: (?<fax>.*)\\n", // Fabulous.com
                "tech-c-name:\\s*(?<name>.+)\\ntech-c-type:\\s*(?<type>.+)\\ntech-c-address:\\s*(?<street>.+)\\ntech-c-postcode:\\s*(?<postalcode>.+)\\ntech-c-city:\\s*(?<city>.+)\\ntech-c-country:\\s*(?<country>.+)\\n(?:tech-c-phone:\\s*(?<phone>.+)\\n)?(?:tech-c-email:\\s*(?<email>.+)\\n)?", // Hetzner
                "Admin Contact Information :[ ]*\\n[ ]+(?<firstname>.*)\\n[ ]+(?<lastname>.*)\\n[ ]+(?<organization>.*)\\n[ ]+(?<email>.*)\\n[ ]+(?<street>.*)\\n[ ]+(?<city>.*)\\n[ ]+(?<postalcode>.*)\\n[ ]+(?<phone>.*)\\n[ ]+(?<fax>.*)\\n\\n", // GAL
                                                                                                                                                                                                                                                     // Communication
                "   Technical contact:\\n      (?<name>.+)\\n      (?<organization>.*)\\n      (?<street>.+)\\n      (?<city>.+) (?<state>\\S+),[ ]+(?<postalcode>.+)\\n      (?<country>.+)\\n      (?<email>.+)\\n      (?<phone>.*)\\n      (?<fax>.*)", // .am
                "Technical:\\n\\s*Name:\\s*(?<name>.*)\\n\\s*Organisation:\\s*(?<organization>.*)\\n\\s*Language:.*\\n\\s*Phone:\\s*(?<phone>.*)\\n\\s*Fax:\\s*(?<fax>.*)\\n\\s*Email:\\s*(?<email>.*)\\n", // EURid
                "\\[Zone-C\\]\\nType: (?<type>.+)\\nName: (?<name>.+)\\n(Organisation: (?<organization>.+)\\n){0,1}(Address: (?<street1>.+)\\n){1}(Address: (?<street2>.+)\\n){0,1}(Address: (?<street3>.+)\\n){0,1}(Address: (?<street4>.+)\\n){0,1}PostalCode: (?<postalcode>.+)\\nCity: (?<city>.+)\\nCountryCode: (?<country>[A-Za-z]{2})\\nPhone: (?<phone>.+)\\nFax: (?<fax>.+)\\nEmail: (?<email>.+)\\n(Remarks: (?<remark>.+)\\n){0,1}Changed: (?<changed>.+)", // DeNIC
                "Technical Contact:\\n   Name:           (?<name>.+)\\n   City:           (?<city>.+)\\n   State:          (?<state>.+)\\n   Country:        (?<country>.+)\\n", // Akky
                                                                                                                                                                                 // (.com.mx)
                "Tech Contact: (?<handle>.+)\\n(?<organization>.+)\\n(?<street1>.+?)(?:,+ (?<street2>.+?)(?:,+ (?<street3>.+?)(?:,+ (?<street4>.+?)(?:,+ (?<street5>.+?)(?:,+ (?<street6>.+?)(?:,+ (?<street7>.+?))?)?)?)?)?)?\\n(?<city>.+),? (?<state>[A-Z]{2,3})(?: [A-Z0-9]+)?\\n(?<postalcode>.+)\\n(?<country>[A-Z]+)\\n", // .co.th,
                                                                                                                                                                                                                                                                                                                                 // format
                                                                                                                                                                                                                                                                                                                                 // 1
                "Tech Contact: (?<handle>.+)\\n(?<organization>.+)\\n(?<street1>.+?)(?:,+ (?<street2>.+?)(?:,+ (?<street3>.+?)(?:,+ (?<street4>.+?)(?:,+ (?<street5>.+?)(?:,+ (?<street6>.+?)(?:,+ (?<street7>.+?))?)?)?)?)?)?\\n(?<city>.+), (?<state>.+)\\n(?<postalcode>.+)\\n(?<country>[A-Z]+)\\n", // .co.th,
                                                                                                                                                                                                                                                                                                         // format
                                                                                                                                                                                                                                                                                                         // 2
                "Tech Contact: (?<handle>.+)\\n(?<organization>.+)\\n(?<street1>.+?)(?:,+ (?<street2>.+?)(?:,+ (?<street3>.+?)(?:,+ (?<street4>.+?)(?:,+ (?<street5>.+?)(?:,+ (?<street6>.+?)(?:,+ (?<street7>.+?))?)?)?)?)?)?, (?<city>.+)\\n(?<postalcode>.+)\\n(?<country>[A-Z]+)\\n", // .co.th,
                                                                                                                                                                                                                                                                                          // format
                                                                                                                                                                                                                                                                                          // 3
                "Tech Contact: (?<handle>.+)\\n(?<street1>.+) (?<city>[^\\s]+)\\n(?<postalcode>.+)\\n(?<country>[A-Z]+)\\n", // .co.th,
                                                                                                                             // format
                                                                                                                             // 4
                "Tech Contact: (?<handle>.+)\\n(?<organization>.+)\\n(?<street1>.+)\\n(?<district>.+) (?<city>[^\\s]+)\\n(?<postalcode>.+)\\n(?<country>[A-Z]+)\\n", // .co.th,
                                                                                                                                                                     // format
                                                                                                                                                                     // 5
                "Tech Contact: (?<handle>.+)\\n(?<organization>.+)\\n(?<street1>.+)\\n(?<street2>.+)\\n(?:(?<street3>.+)\\n)?(?<city>.+)\\n(?<postalcode>.+)\\n(?<country>[A-Z]+)\\n", // .co.th,
                                                                                                                                                                                       // format
                                                                                                                                                                                       // 6
                "   Technical Contact:\\n      (?<name>.+)  (?<email>.+)\\n      (?<phone>.*)\\n      (?<fax>.*)\\n", // .com.tw
                                                                                                                      // (Western
                                                                                                                      // registrars)
                "Technical Contact Information:\\n\\n(?:Given name: (?<firstname>.+)\\n)?(?:Family name: (?<lastname>.+)\\n)?(?:Company name: (?<organization>.+)\\n)?Address: (?<street>.+)\\nCountry: (?<country>.+)\\nPhone: (?<phone>.*)\\nFax: (?<fax>.*)\\nEmail: (?<email>.+)\\n(?:Account Name: (?<handle>.+)\\n)?", // HKDNR
                                                                                                                                                                                                                                                                                                                             // (.hk)
                "TECH ID:(?<handle>.+)\\nTECH Name:(?<name>.*)\\n(?:TECH Organization:(?<organization>.*)\\n)?TECH Street1:(?<street1>.+?)\\n(?:TECH Street2:(?<street2>.+?)\\n(?:TECH Street3:(?<street3>.+?)\\n)?)?TECH City:(?<city>.+)\\nTECH State:(?<state>.*)\\nTECH Postal Code:(?<postalcode>.+)\\nTECH Country:(?<country>[A-Z]+)\\nTECH Phone:(?<phone>.*?)\\nTECH Fax:(?<fax>.*)\\nTECH Email:(?<email>.+)\\n" // Realtime
        });
    }
}
